sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-638.pdf --upload --lsstdoc LDM-638.tex --env=travis --ltd-product ldm-638"
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="ldm-638"
    # AWS and LTD Keeper credentials as encrypted secrets here
    - secure: "knD+YM4Fi1E9bNy3MxHsCGnLUzWOrzzd18FSxnJm5+YWWH95BlPpwpZuc3jiWcl0QEQ0rmIX4adfii+xT0KffzDUdFm1WF1OBNKtS0OFuwFt5ehVDVooa9BmPWFIJ4OhXTM4ZBFJoGSbwVtyRWKdJ4mF3v1yYvnnxu+1F8dGJt5CzS6DZShIabU+ltPPalSB37pvkWI2dfzWBRzmDvBprO5OFimslPTk1X7lbWc/8DDsVwPxHqF0X1sPUGjBGrs03LdatYIv2wbJXJj4SCZsOZCfLpOIqv21xFz+2lEq59E2Z3OcOrf2o4gYN+EAQvhveo7piBUtqwmCWhLoM04lRiZqWUyInVvNK2sMX6W/ZWaHrdqIYkS5zY18Bo3kqCz9q323gzJEdtnZ+a7tfdVj3/OYQU9nFVpDB+YY3JgBSBLhGa9fQI0DJl4hYtiC5073Mk2RQvHiszgmjLx+h28CbbVbewPj7SzBg0x5+RoH1qfr0vlPmy1N6NhJOcu7edSz7gxRFAI80gaI6jineAsujTW9kRfP4Mx3DMbORXTPw7FF1b5dMui9QJAev2NyRqPIJXIuD/L8ahOaKfQol77k0EIn4224DCaGrp9mA0JJzAe/xu7tNPqlg2ogpMWUoigfrm/eleZm/+lQF34ojy2ySNX3/1qsqkmH7FhJ9r7Oqbg="
    - secure: "GR6RqDCPF+wP4mfWxutDrMsvFQw4xy51qw0iSlNvnCYpFJYVHDXgN1EpLdEL0QGcboQDPqfF7MIHfA1VddLui/DkbSRSCwqhO0DMmcXs8DVIqxktC3FG5w7yJmzD5ggBD0jaUcBzknhe65s/h4ggBn51d32ENXtPD7oLOqCeBFElbXobsi57z/1XCoH1ejLFnkq1qYBLvG1u0ZWbkcElUzFVtzyBjEY0lBgmCiGJ/Sg3n0OMGQdTH8jNCf1AJKr2R/g+fTa16NJwREFOkpp4tLff1ZnqwtDz6HOq+zv2s4d6lAdEwSf4SYoNYQ57QLhig5m8oKZuAMoGggfKM+phj5CKsfq2+8naqtakLLS6QZhcnFQ1QdSYOZ0aHhEYAKiz9UCIDU6zhivdF4/y0rKW3qoQbkNA1hCXpd+tI5tfNPMMY2flRvkz/sBVgG2N135QY5xDqOWMsd4enaLldnuxMwAZ6TskrphwhtsSvKCn3xWWWjAR9duZkdB4aLmZJhNYlNMm3z1ELSJYlhoYO52ZFgOGM+koN1Nq2FHjfZw2zO+qCYslD7mTeVhqlr4ETD5YJykLeljyGZRlUTo3w9fqZBEriDeQ18gtrZLd7JLYzFXuORzMt2g7M1aXO/sye0ORjmTpY8z+Gk4ZLABIuFHsQgz9VDB3UiM087xSHnnXSMg="
